### ISSUE TITLE
docker-compose restart yapi-web，查看日志配置还是之前的并且会抛出Error初始化管理员账号失败

### ISSUE THREAD

**Issue by yinghuijian** [fjc0k/docker-YApi#12]
抛出异常的日志是这样的：
/yapi/vendors/server/install.js:146
yapi-web      |           throw new Error(`初始化管理员账号 "${yapi.WEBCONFIG.adminAccount}" 失败, ${err.message}`); // eslint-disable-line
yapi-web      |                 ^
yapi-web      |
yapi-web      | Error: 初始化管理员账号 "admin@qq.com" 失败, E11000 duplicate key error collection: yapi.user index: email_1 dup key: {email: "admin@qq.com" }
yapi-web      |     at /yapi/vendors/server/install.js:146:17
yapi-web      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by fjc0k** [comment]
初始化管理员账号这个不用管，每次启动都会尝试安装的，本身没有任何影响。

**Comment by fjc0k** [comment]
如果要一切从头，把现在的删了，重新 clone 一遍安装看看

**Comment by yinghuijian** [comment]
> 如果要一切从头，把现在的删了，重新 clone 一遍安装看看

好的
