### ISSUE TITLE
使用插件后，在哪里配置插件？

### ISSUE THREAD

**Issue by 715731281** [fjc0k/docker-YApi#15]
在docker-compose.yaml里面添加了插件yapi-plugin-webhook，并且重启后安装成功。
但是该插件需要配置，那么在docker exec进入容器后应该配置哪个文件呢？ #

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/74316400-6dcfac00-4db4-11ea-8746-13510926edf9.png)
