### ISSUE TITLE
增加volumes配置报错

### ISSUE THREAD

**Issue by blackkeai** [fjc0k/docker-YApi#18]
compose 文件中添加，启动时报错

volumes:
      - /Users/minty/docker_share/yapi:/yapi

**Comment by fjc0k** [comment]
这肯定报错啊，不要这样搞。

**Comment by blackkeai** [comment]
我自己的compose也是这么写的，没问题呀？那这个要怎么做？

**Comment by fjc0k** [comment]
去掉啊。

**Comment by blackkeai** [comment]
关键是我想共享目录啊，去掉了多麻烦。

**Comment by fjc0k** [comment]
你不去掉就没办法了。
