### ISSUE TITLE
从1.8.5升级到了1.8.8，数据丢失了

### ISSUE THREAD

**Issue by u4989190** [fjc0k/docker-YApi#19]
按照文档升级，执行了docker-compose pull yapi-web, down , up,结果以前的数据全没了，查看docker log如下。

#--------------------------------------------------------------------

#--------------------------------------------------------------------
查了一下命令，docker-compose down会删除现有的数据啊？这里应该执行docker-compose stop吧？？？？

**Comment by fjc0k** [comment]
你如果没把数据库文件映射出来当然会啊，发出你的 docker-compose.yml

**Comment by u4989190** [comment]
我查了一下volume，旧的还在。等我po一下我的compose文件

**Comment by fjc0k** [comment]
- yapi-web-data:/data/db/web
- yapi-mongo-data:/data/db/mongo

你这瞎搞？

**Comment by fjc0k** [comment]
如果要改，麻烦搞清楚内部目录结构。

**Comment by fjc0k** [comment]
~yapi-web-data:/data/db/web~
`yapi-mongo-data:/data/db/mongo` --> `yapi-mongo-data:/data/db`

**Comment by u4989190** [comment]
这个是之前参考别的compose文件自己改的，确实没搞清楚原理。我以为是volume放在内部容器的路径。可否给个解决思路吗。docker这里我就简单自己配过几次，没有深入学习。本来准备看一下docker in Action 那本书的，最近在看计算机网络，可能还得往后推。

**Comment by u4989190** [comment]
貌似找到解决方法了，好像可以用external 这个属性。
https://docs.docker.com/compose/compose-file/#external

不过在试的过程中，把volume重新建了一次，覆盖了以前的volume。之前对compose的每个属性都不了解，导致操作失误。应该先clone一份volume的。
