### ISSUE TITLE
添加插件报错

### ISSUE THREAD

**Issue by LookFor1231** [fjc0k/docker-YApi#2]
提示：找不到 yapi-pluin-dingding

**Comment by fjc0k** [comment]
https://github.com/fjc0k/docker-YApi#%E5%AE%89%E8%A3%85

**Comment by LookFor1231** [comment]
` // 需安装的插件列表
  plugins: [
  {
       "name": "dingding" ,
        "options": {
          "host": "http://yapi.xxxx.com"
        }
     },
     { name: 'import-swagger-customize' }
  ]`
其他没改，config.js弄成这样
在执行：Step 11/18 : RUN npm run build-client
 ---> Running in 45bcf42b2a96
> yapi-vendor@1.8.1 build-client /yapi/vendors
> NODE_ENV=production ykit pack -m
提示：internal/modules/cjs/loader.js:716
 throw err;
 ^
Error: Cannot find module 'yapi-plugin-dingding'

**Comment by fjc0k** [comment]
文档有说你要 docker build 嘛？

**Comment by LookFor1231** [comment]
build-client? 就是在dockerfile和start.js里啊。

**Comment by fjc0k** [comment]
请从头到尾看一遍文档或者把你的操作步骤列举下来。你出现了 `RUN`，那你肯定是自己 build 镜像了，但文档里并没有让你自己构建镜像

**Comment by LookFor1231** [comment]
1：下载你的源码，发布到docker镜像中
2：没添加插件的时候，是可以正常编译发布的。
3：在config.js里，按照文档的，把dingding插件加进去，结果就显示：Cannot find module 'yapi-plugin-dingding'
我qq:82911126

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/63408488-c2a3f280-c421-11e9-83ae-1c6036af3bc7.png)

你为什么要自己发布呢？

**Comment by LookFor1231** [comment]
你的意思是直接拉取你的镜像么

**Comment by fjc0k** [comment]
这本来就是一个 docker 镜像的开源项目，而不是 Dockerfile 的开源项目。你如果要自己定制发布镜像，你肯定得自己弄/改 Dockerfile
