### ISSUE TITLE
yapi-web启动失败了

### ISSUE THREAD

**Issue by LL3706** [fjc0k/docker-YApi#22]
我的配置文件
`version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@163.com
      - YAPI_ADMIN_PASSWORD=admin
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[{"name":"add-user"}]
      - YAPI_NPM_REGISTRY=https://registry.npm.taobao.org
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
`
[
![image](https://user-images.githubusercontent.com/22722591/78538288-57c5f100-7823-11ea-987c-356cba266515.png)
](url)

**Comment by LL3706** [comment]
哪里配置的不对吗，请大佬支持下

**Comment by LL3706** [comment]
mongo 启动是好的
[
![image](https://user-images.githubusercontent.com/22722591/78538616-d9b61a00-7823-11ea-80cc-11d7134e021f.png)
](url)

**Comment by LL3706** [comment]
我加了start.js 还是不行，一样的错误
[
![image](https://user-images.githubusercontent.com/22722591/78541651-8c887700-7828-11ea-91a7-538088c43861.png)
](url)

**Comment by fjc0k** [comment]
你什么都没动过？编辑过没？在什么上用什么编辑的？

**Comment by LL3706** [comment]
我只改了dokcer-compose.yml文件

**Comment by LL3706** [comment]
js 没有改过，是复制粘贴进去的

**Comment by LL3706** [comment]
用服务器vim 命令修改的yml 文件

**Comment by fjc0k** [comment]
你是不是把换行符号从 lf 整成 crlf 了，你重新 clone，啥都别动再试试，ok那就是你编辑器原因

**Comment by LL3706** [comment]
把原来文件夹都删掉吗，我试试

**Comment by LL3706** [comment]
我重新clone 了
[
![image](https://user-images.githubusercontent.com/22722591/78548357-4258c300-7833-11ea-8bfc-239fc181cb05.png)
](url)

**Comment by LL3706** [comment]
我重新修改yml 文件吗

**Comment by fjc0k** [comment]
啥都别动 启动看看

**Comment by LL3706** [comment]
好的

**Comment by LL3706** [comment]
我啥都没有动
[
![image](https://user-images.githubusercontent.com/22722591/78548962-30c3eb00-7834-11ea-913f-eea24e48d985.png)
](url)

**Comment by LL3706** [comment]
我刚才用vim 看了一眼配置文件yml，没有改，难道这也影响吗

**Comment by LL3706** [comment]
我感觉说不通啊，mongo 服务都是好的，就yapi-web 服务启动不了

**Comment by LL3706** [comment]
[
![image](https://user-images.githubusercontent.com/22722591/78549621-41289580-7835-11ea-8075-77880781cb7f.png)
](url)

**Comment by LL3706** [comment]
[
![image](https://user-images.githubusercontent.com/22722591/78549875-ae3c2b00-7835-11ea-81de-88880d44df33.png)
](url)

**Comment by fjc0k** [comment]
建议你搜索：

standard_init_linux.go:190: exec user process caused "exec format error"

自行解决

**Comment by fjc0k** [comment]
建议你升级下 docker 再试试


![image](https://user-images.githubusercontent.com/13151189/78550219-44705100-7836-11ea-8e50-5c5222756f95.png)

**Comment by LL3706** [comment]
我搜了，说是脚本前面没有加#!bin/bash ,但是试了下，还是那个错误

![image](https://user-images.githubusercontent.com/22722591/78550270-5baf3e80-7836-11ea-9d3f-0756f986b6bd.png)

**Comment by LL3706** [comment]
好吧，我试试升级docker

**Comment by LL3706** [comment]
![image](https://user-images.githubusercontent.com/22722591/78566083-527f9b00-7851-11ea-8a2d-9d17b37252f5.png)
我升级了版本但是还是报原来的错，太匪夷所思了

**Comment by LL3706** [comment]
[
![image](https://user-images.githubusercontent.com/22722591/78566324-a12d3500-7851-11ea-8d89-6875c34ca8df.png)
](url)

**Comment by LL3706** [comment]
![image](https://user-images.githubusercontent.com/22722591/78574411-8dd39700-785c-11ea-99ca-617db105204e.png)
已经升级到最新版本的

**Comment by LL3706** [comment]
大佬，我查了资料，这个错误是指容器镜像格式错误，意思就是说这个用的是X86的镜像，需要替换成ARM镜像，现在问题是有没有ARM的镜像

**Comment by fjc0k** [comment]
好的，找到问题出在哪里就好办了，晚上搞搞

**Comment by LL3706** [comment]
好的，辛苦了，这是源头https://bbs.huaweicloud.com/forum/thread-26434-1-1.html
[
![image](https://user-images.githubusercontent.com/22722591/78861682-fc387500-7a67-11ea-92fa-649848309c71.png)
](url)

**Comment by LL3706** [comment]
> 好的，找到问题出在哪里就好办了，晚上搞搞

大佬，有思路吗

**Comment by fjc0k** [comment]
在搞

**Comment by fjc0k** [comment]
@LL3706 老哥，试试 beta 版，把 docker-compose 里的  `jayfong/yapi:latest` 改成 `jayfong/yapi:beta` 即可。

![image](https://user-images.githubusercontent.com/13151189/78910412-878d2700-7ab7-11ea-93d0-c13e348cefe3.png)

**Comment by LL3706** [comment]
> @LL3706 老哥，试试 beta 版，把 docker-compose 里的 `jayfong/yapi:latest` 改成 `jayfong/yapi:beta` 即可。
> 
> ![image](https://user-images.githubusercontent.com/13151189/78910412-878d2700-7ab7-11ea-93d0-c13e348cefe3.png)

牛逼，辛苦哈

**Comment by fjc0k** [comment]
可以不？

**Comment by LL3706** [comment]
> 可以不？

[
![image](https://user-images.githubusercontent.com/22722591/78913520-b60d0100-7abb-11ea-9bd7-61432d12e9d7.png)
](url)正在进行中

**Comment by LL3706** [comment]
> > 可以不？
> 
> [ ![image](https://user-images.githubusercontent.com/22722591/78913520-b60d0100-7abb-11ea-9bd7-61432d12e9d7.png) ](url)正在进行中，网速慢，稍等

见证奇迹的时刻

**Comment by LL3706** [comment]
> > > 可以不？
> > 
> > 
> > [ ![image](https://user-images.githubusercontent.com/22722591/78913520-b60d0100-7abb-11ea-9bd7-61432d12e9d7.png) ](url)正在进行中，网速慢，稍等
> 
> 见证奇迹的时刻

[
![image](https://user-images.githubusercontent.com/22722591/78913745-0a17e580-7abc-11ea-928f-36440e218bff.png)
](url)
为啥拉不下来

**Comment by fjc0k** [comment]
😄 超时了，最好给 docker 搞个国内镜像

**Comment by LL3706** [comment]
> 😄 超时了，最好给 docker 搞个国内镜像

修改daemon.json 文件吗

**Comment by LL3706** [comment]
> > 😄 超时了，最好给 docker 搞个国内镜像
> 
> 修改daemon.json 文件吗

但是你上传的是dockerHub 啊

**Comment by fjc0k** [comment]
https://yq.aliyun.com/articles/29941

**Comment by fjc0k** [comment]
不用阿里也有其他家的，自行选择一个源

**Comment by LL3706** [comment]
> 不用阿里也有其他家的，自行选择一个源

[

](url)
这个行不

**Comment by fjc0k** [comment]
你试试吧

**Comment by LL3706** [comment]
> 你试试吧

![image](https://user-images.githubusercontent.com/22722591/78915320-519f7100-7abe-11ea-9e52-8be0d9900a09.png)

**Comment by LL3706** [comment]
> > 你试试吧
> 
> ![image](https://user-images.githubusercontent.com/22722591/78915320-519f7100-7abe-11ea-9e52-8be0d9900a09.png)

这个应该拉下来

**Comment by LL3706** [comment]
> > > 你试试吧
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/22722591/78915320-519f7100-7abe-11ea-9e52-8be0d9900a09.png)
> 
> 这个应该拉下来

太慢了，明天看结果吧，感谢大佬的支持

**Comment by fjc0k** [comment]
阿里快呀  😂

**Comment by LL3706** [comment]
> 阿里快呀 😂

我原来就是用ali 的镜像加速器，结果拉不下来

**Comment by LL3706** [comment]
> > 阿里快呀 😂
> 
> 我原来就是用ali 的镜像加速器，结果拉不下来

![image](https://user-images.githubusercontent.com/22722591/78917475-79dc9f00-7ac1-11ea-9ed2-c4241219cbd7.png)
终于不报那个错了，但是还是启动不了

**Comment by LL3706** [comment]
这是新的错误
<--- Last few GCs --->
yapi-web      | 
yapi-web      | 
yapi-web      | <--- JS stacktrace --->
yapi-web      | 
yapi-web      | 
yapi-web      | #
yapi-web      | # Fatal process OOM in insufficient memory to create an Isolate
yapi-web      | #

**Comment by fjc0k** [comment]
内存不足，还是换一台服务器吧。话说你这服务器啥配置啊

**Comment by LL3706** [comment]
> 内存不足，还是换一台服务器吧。话说你这服务器啥配置啊
内存1G ,我在别的服务器上安装好，把镜像复制过来能运行吗

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/78955661-7cb3b000-7b12-11ea-86a9-bb49f016f892.png)

你可以把插件去掉试试

**Comment by LL3706** [comment]
> ![image](https://user-images.githubusercontent.com/13151189/78955661-7cb3b000-7b12-11ea-86a9-bb49f016f892.png)
> 
> 你可以把插件去掉试试

**Comment by fjc0k** [comment]
? 去掉插件好了？

**Comment by LL3706** [comment]
> ? 去掉插件好了？

正在进行中。。。稍等。。。

**Comment by LL3706** [comment]
> > ? 去掉插件好了？
> 
> 正在进行中。。。稍等。。。

现在华为云 挂了。。。。

**Comment by fjc0k** [comment]
挂了。。。

**Comment by LL3706** [comment]
> 挂了。。。
去掉插件还是报这错
yapi-web      | <--- Last few GCs --->
yapi-web      | 
yapi-web      | 
yapi-web      | <--- JS stacktrace --->
yapi-web      | 
yapi-web      | 
yapi-web      | #
yapi-web      | # Fatal process OOM in insufficient memory to create an Isolate
yapi-web      | #
yapi-web      | 
yapi-web      | 
yapi-web      | <--- Last few GCs --->
yapi-web      | 
yapi-web      | 
yapi-web      | <--- JS stacktrace --->
yapi-web      | 
yapi-web      | 
yapi-web      | #
yapi-web      | # Fatal process OOM in insufficient memory to create an Isolate
yapi-web      | #
yapi-web      |

**Comment by LL3706** [comment]
> > 挂了。。。
> > 去掉插件还是报这错
> > yapi-web      | <--- Last few GCs --->
> > yapi-web      |
> > yapi-web      |
> > yapi-web      | <--- JS stacktrace --->
> > yapi-web      |
> > yapi-web      |
> > yapi-web      | #
> > yapi-web      | # Fatal process OOM in insufficient memory to create an Isolate
> > yapi-web      | #
> > yapi-web      |
> > yapi-web      |
> > yapi-web      | <--- Last few GCs --->
> > yapi-web      |
> > yapi-web      |
> > yapi-web      | <--- JS stacktrace --->
> > yapi-web      |
> > yapi-web      |
> > yapi-web      | #
> > yapi-web      | # Fatal process OOM in insufficient memory to create an Isolate
> > yapi-web      | #
> > yapi-web      |
能不能在别的服务器上把镜像搞好，然后复制到这台服务器上，能运行吗

**Comment by fjc0k** [comment]
不行哦

**Comment by LL3706** [comment]
> 不行哦

![image](https://user-images.githubusercontent.com/22722591/78961064-a543a600-7b22-11ea-980c-0f4a084458f1.png)
你在这里说不是可以吗

**Comment by fjc0k** [comment]
我说的是插件，把插件打包进镜像，你这不要插件镜像都启动不了。

**Comment by LL3706** [comment]
> 我说的是插件，把插件打包进镜像，你这不要插件镜像都启动不了。

好吧，明白了，docker-compose 用不了安装yapi

**Comment by fjc0k** [comment]
你可以考虑升级个 0.5G 的内存

**Comment by LL3706** [comment]
> 你可以考虑升级个 0.5G 的内存

好的，感谢您的指导
