### ISSUE TITLE
mongodb无法远程连接，只能通过进入容器

### ISSUE THREAD

**Issue by li-ml** [fjc0k/docker-YApi#23]
想导出mongodb的数据，发现只能进入容器中查看，远程无法连接。

**Comment by fjc0k** [comment]
请自行了解 docker-compose 中 expose 和 ports 的区别，并修改你的 docker-compose.yml 文件，并且请悉知开启远程务必打开密码访问，否则数据被删只需分分钟。

**Comment by li-ml** [comment]
已经加了ports，已经解决，谢谢

**Comment by dybxin** [comment]
> 已经加了ports，已经解决，谢谢
能否提供一份你改下后的docker-compose.yml 文件

**Comment by dybxin** [comment]
> 已经加了ports，已经解决，谢谢

能否提供？一份你改下后的docker-compose.yml 文件
