### ISSUE TITLE
How to enable authentication on MongoDB through Docker?

### ISSUE THREAD

**Issue by dybxin** [fjc0k/docker-YApi#30]
version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@docker.yapi
      - YAPI_ADMIN_PASSWORD=adm1n
      - YAPI_CLOSE_REGISTER=false
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_DB_USER=root
      - YAPI_DB_PASS=0000
      - YAPI_DB_AUTH_SOURCE=admin
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
    command: mongod --auth

**Comment by fjc0k** [comment]
没有必要，本来就没暴露给外网，如果需要，请自行查询相关资料
