### ISSUE TITLE
MongoNetworkError: Authentication failed., mongodb Authentication failed

### ISSUE THREAD

**Issue by dybxin** [fjc0k/docker-YApi#32]
Attaching to yapi-web
yapi-web      | 启动引导服务...
yapi-web      | 写入配置...
yapi-web      | {
yapi-web      |   "plugins": [
yapi-web      |     {
yapi-web      |       "name": "add-user",
yapi-web      |       "options": {}
yapi-web      |     }
yapi-web      |   ],
yapi-web      |   "adminAccount": "admin@docker.yapi",
yapi-web      |   "adminPassword": "adm1n",
yapi-web      |   "closeRegister": true,
yapi-web      |   "db": {
yapi-web      |     "servername": "yapi-mongo",
yapi-web      |     "port": 27017,
yapi-web      |     "DATABASE": "yapi",
yapi-web      |     "user": "root",
yapi-web      |     "pass": "0000",
yapi-web      |     "authSource": "admin"
yapi-web      |   },
yapi-web      |   "mail": {
yapi-web      |     "enable": false,
yapi-web      |     "auth": {}
yapi-web      |   },
yapi-web      |   "ldapLogin": {
yapi-web      |     "enable": false
yapi-web      |   },
yapi-web      |   "port": 3000
yapi-web      | }
yapi-web      | 等待 MongoDB 服务可用...
yapi-web      | 安装 YApi 插件...
yapi-web      | 尝试安装 YApi...
yapi-web      | + node '--unhandled-rejections=strict' /yapi/vendors/server/install.js
yapi-web      | 
yapi-web      | error: MongoNetworkError: Authentication failed., mongodb Authentication failed
yapi-web      | 
yapi-web      | log: mongodb load success...
yapi-web      | 
yapi-web      | /yapi/vendors/server/install.js:151
yapi-web      |       throw new Error(err.message);
yapi-web      |             ^
yapi-web      | 
yapi-web      | Error: Cannot read property 'collection' of undefined
yapi-web      |     at /yapi/vendors/server/install.js:151:13
yapi-web      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
yapi-web      | 
yapi-web      | 关闭引导服务...
yapi-web      | 尝试启动 YApi...
yapi-web      | log: -------------------------------------swaggerSyncUtils constructor-----------------------------------------------
yapi-web      | log: 服务已启动，请打开下面链接访问: 
yapi-web      | http://127.0.0.1:3000/
yapi-web      | error: MongoNetworkError: Authentication failed., mongodb Authentication failed
yapi-web      | log: mongodb load success...
yapi-web      | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
yapi-web      |     at /yapi/vendors/exts/yapi-plugin-advanced-mock/server.js:24:38
yapi-web      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
yapi-web      | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
yapi-web      | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
yapi-web      | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
yapi-web      |     at /yapi/vendors/exts/yapi-plugin-statistics/server.js:12:38
yapi-web      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
yapi-web      | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
yapi-web      | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
yapi-web      |     at /yapi/vendors/exts/yapi-plugin-wiki/server.js:7:38
yapi-web      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
yapi-web      | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
yapi-web      | (node:1) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by fjc0k** [comment]
自身配置问题，自行解决。

**Comment by greper** [comment]
> 自身配置问题，自行解决。

我也遇到同样的问题
我查看源码发现，并不是我们配置问题，而是config.json生成的位置不对
生成的config.json 位于/yapi/config.json目录下
而执行install时，/yapi/vendors/server/yapi.js 读取的是 /yapi/vendors/config.json
所以实际问题是config.json生成的位置错了

**Comment by fjc0k** [comment]
@greper install 的 config 来自 yapi，yapi 的 config 来自 /yapi/config.json，如果生成位置不对，那么大部分人都会出现问题，而不是个别人出现问题。
https://github.com/fjc0k/YApi-X/blob/master/server/yapi.js#L4

**Comment by greper** [comment]
> @greper install 的 config 来自 yapi，yapi 的 config 来自 /yapi/config.json，如果生成位置不对，那么大部分人都会出现问题，而不是个别人出现问题。
> https://github.com/fjc0k/YApi-X/blob/master/server/yapi.js#L4
不好意思，搞错了，我再看看

**Comment by YvesDev** [comment]
检查mongodb的账号及密码，检查yapi的config.json的"user":"pass":是否正确，并且"authSource": "admin"

**Comment by qiusheng2011** [comment]
mongo 账号和密码都对， 命令行能登录进去， config.json 也对，但是就是启动失败啊

**Comment by zhaoming-mike** [comment]
这么简单的问题，host 你填的是 127.0.0.1 ，容器里面能访问的到吗？
