### ISSUE TITLE
Can not change yapi-web port

### ISSUE THREAD

**Issue by gary101** [fjc0k/docker-YApi#34]
I want to change yapi-web port since the default port **40001** is not friendly.

What I did is modify the **"ports"** value  under **"yapi-web"** in  `docker-composer.yml` file:

> services:
>   yapi-web:
>     image: jayfong/yapi:latest
>     container_name: yapi-web
>     ports:
>       - 3000:3000
>     ...

It is supposed to be available from remote by visiting url:  **http://SERVER-IP:3000/** , 
but is unavailable even though I restarted it ( `docker-compose restart yapi-web` ) !

So,**what is the right way to change the yapi-web port**?

Thanks a lot!

**Comment by fjc0k** [comment]
```yml
ports:
  - 40001:3000
```

->

```yml
ports:
  - 4000:3000
```
