### ISSUE TITLE
部署后一直提示等待mongodb服务

### ISSUE THREAD

**Issue by Zohar727** [fjc0k/docker-YApi#37]
**我的配置：**
version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=
      - YAPI_ADMIN_PASSWORD=
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_DB_USER=admin
      - YAPI_DB_PASS=admin
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped

**部署后运行docker ps**
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                           PORTS                     NAMES
753046c7b5ca        jayfong/yapi:latest   "docker-entrypoint.s…"   17 seconds ago      Up 15 seconds                    0.0.0.0:40001->3000/tcp   yapi-web
ad183c729ef6        mongo:latest          "docker-entrypoint.s…"   28 minutes ago      Restarting (14) 38 seconds ago                             yapi-mongo

按照文档一步步来的，请教一下接下来该怎么操作呢？

**Comment by fjc0k** [comment]
运行 `docker-compose logs` 看看报错信息
