### ISSUE TITLE
在 k8s 上启动报错怎么办？

### ISSUE THREAD

**Issue by yizhishang** [fjc0k/docker-YApi#4]
使用docker-compose启动正常，
但是在kubernates启动报错，如下图所示
![image](https://user-images.githubusercontent.com/12756407/66881439-63192c00-eff9-11e9-94ed-da6d80d5bea8.png)

**Comment by fjc0k** [comment]
你是用的自己构建的还是官方的镜像？

**Comment by yizhishang** [comment]
从官方下载的jayfong/yapi:latest

**Comment by yizhishang** [comment]
我自己根据你提供的脚本构建的镜像，也是相同的问题，docker-compose没问题，上k8s就是如图一样的错误

**Comment by yizhishang** [comment]
> 你是用的自己构建的还是官方的镜像？

你有尝试过吗？这种现象太奇怪了

**Comment by yizhishang** [comment]
> 你是用的自己构建的还是官方的镜像？

大佬知道这是什么问题不

**Comment by fjc0k** [comment]
请假搬家呢 老哥 暂时没时间调查

**Comment by yizhishang** [comment]
找到问题所在了，挂载的config.js除了问题，将/yapi下面的文件覆盖了，我改到挂载到其他的地方，修改了start.js加载config.js的路径就ok了

**Comment by fjc0k** [comment]
棒！
