### ISSUE TITLE
can not install  any plugin

### ISSUE THREAD

**Issue by AllenAlan** [fjc0k/docker-YApi#44]
![image](https://user-images.githubusercontent.com/18695383/84460634-09a6f100-ac9d-11ea-8632-d37a629502d3.png)
`- YAPI_PLUGINS=[{"name":"gitlab","options":{}}]`
can not install  any plugin

**Comment by fjc0k** [comment]
能详细点？

**Comment by AllenAlan** [comment]
> ![image](https://user-images.githubusercontent.com/18695383/84460634-09a6f100-ac9d-11ea-8632-d37a629502d3.png)
> `- YAPI_PLUGINS=[{"name":"gitlab","options":{}}]`
> can not install any plugin
