### ISSUE TITLE
我在执行compose文件时，npm会卡住不动，这是什么原因呢？

### ISSUE THREAD

**Issue by ohohok** [fjc0k/docker-YApi#49]
Building yapi
Step 1/4 : FROM node:12-alpine
 ---> 057fa4cc38c2
Step 2/4 : COPY repositories /etc/apk/repositories
 ---> Using cache
 ---> 3c404293437f
Step 3/4 : RUN npm config set registry https://registry.npm.taobao.org && npm install -g yapi-cli --registry https://registry.npm.taobao.org
 ---> Running in 1b9b5dd8a20f

**Comment by fjc0k** [comment]
这明显不是本项目的代码，你问错地儿了吧

**Comment by ohohok** [comment]
> 这明显不是本项目的代码，你问错地儿了吧

没有啊，docker-compose up 的时候出现的，我只是发现npm install 会卡主不动

**Comment by ohohok** [comment]
> > 这明显不是本项目的代码，你问错地儿了吧
> 
> 没有啊，docker-compose up的时候出现的，我只是发现npm install会卡主不动

sorrry，我貌似真的问错了

**Comment by ohohok** [comment]
我现在使用了您的项目启动起来了，不过我有个问题想问你，compose中的mongo expose27017端口，这个跟我本地的mongo不会端口冲突吗？

**Comment by fjc0k** [comment]
expose 只在这个 compose 内部使用，port 才会影响外部。

**Comment by ohohok** [comment]
> 暴露只在这个compose内部使用，port才会影响外部。

噢噢，我一直都用port，没有用links那些，那我现在在别的机器访问不到，这要怎么处理？就类似于我想设置成0.0.0.0:40001这样，那其他人都可以访问了

**Comment by ohohok** [comment]
已经解决了，谢谢这么快速地回答我
