### ISSUE TITLE
安装有插件时启动花费很长时间怎么解决？

### ISSUE THREAD

**Issue by yizhishang** [fjc0k/docker-YApi#5]
兄弟，请问下，每次启动都是重新安装插件，这个步骤需要浪费大量的时间，还有优化的空间吗？
是否可以预先定义好插件，在打docker镜像的时候将插件也弄好，这样每次启动就可以节省很多时间了

**Comment by fjc0k** [comment]
可以的。

把我这边构建好的镜像替换成你自己构建的镜像，即将默认的 `docker-compose.yml` 中的 `image: jayfong/yapi:latest` 替换为 `build: .` 即可，但首次构建时间会略长。

**Comment by fjc0k** [comment]
再仔细看了看逻辑，目前不可以，除非你手动改 `Dockerfile` 提前安装插件，还要改 `start.js` 禁止运行时安装插件。

**Comment by yizhishang** [comment]
我想请教下，yapi的这些插件，是否依赖于config.js的配置。
是否可以在修改Dockerfile中，添加npm install interface-oauth2-token gitlab-oauth2，就可以了，即使我在config.json没有添加具体的配置信息

**Comment by yizhishang** [comment]
在重新启动的时候，node可以检测到已经有了某些插件的依赖包，直接读取config配置就行了

**Comment by yizhishang** [comment]
可以这样吗

**Comment by fjc0k** [comment]
yapi 没有插件自动发现机制的，必须在配置文件定义。

**Comment by yizhishang** [comment]
那就悲剧了

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/69293497-fa4e5080-0c43-11ea-8dfb-573fc8517255.png)
把这段代码去掉也不行？

**Comment by yizhishang** [comment]
在start.js中将安装插件的逻辑去掉，config.js还是照样配置，可行吗

**Comment by fjc0k** [comment]
哎，你这么一说，可以把容器内部的 `/yapi` 目录挂载出来，这样重新运行时，安装会很快的。

**Comment by fjc0k** [comment]
这样试试，其他不用动，改 `docker-compose.yml`，`yapi-web` 加上:
```yml
volumes:
  - ./data/yapi:/yapi
```

**Comment by yizhishang** [comment]
好吧，这些是一种方案
肯定可以的，就跟本地启动源代码一样

**Comment by fjc0k** [comment]
嗯嗯，优化下：
```yml
volumes:
  - ./data/yapi-vendors:/yapi/vendors
```

**Comment by yizhishang** [comment]
只能这样了
