### ISSUE TITLE
安装yapi-x谷歌插件后，仍无法上传文件

### ISSUE THREAD

**Issue by fengbinTester** [fjc0k/docker-YApi#52]
版本是1.9.2，修改 YApi 源码，删除文件 client/components/Postman/Postman.js 的第 875 行，然后将它下面代码的注释取消掉即可！然后重启了Yapi，但是上传文件接口仍展示因Chrome最新版安全策略限制，不再支持文件上传

**Comment by fjc0k** [comment]
那你何不直接使用 yapi-x，他直接支持docker安装，插件也原生支持。

**Comment by fengbinTester** [comment]
![image](https://user-images.githubusercontent.com/42330540/92301129-79becd80-ef93-11ea-9a91-0dddead10249.png)
使用了试用地址，也是如此

**Comment by fjc0k** [comment]
https://github.com/fjc0k/YApi-X
