### ISSUE TITLE
电脑关机重启后  启动yapi  mongo服务就一直在循环启动

### ISSUE THREAD

**Issue by tangqiu0205** [fjc0k/docker-YApi#64]
是我操作有误吗

![image](https://user-images.githubusercontent.com/37826977/102186454-9bfaac80-3eed-11eb-93a2-2a5bb1058423.png)

**Comment by Maqiushi** [comment]
考虑使用docker service，自动重启，位置网络状态。另，注意mongodb mount的数据文件。
