### ISSUE TITLE
阿里云服务器 部署时 访问502

### ISSUE THREAD

**Issue by HiWilliam** [fjc0k/docker-YApi#7]
在阿里云上部署，配置npm的镜像源和安装的插件 。docker-compose up后服务正常启动，使用nginx代理，访问出现502。删除compose文件中npm镜像，以及设置YAPI_PLUGINS默认后，重新部署，可以正常访问

**Comment by fjc0k** [comment]
建议 `docker-compose logs yapi-web` 查看出错日志，好对症下药。
