### ISSUE TITLE
老哥，是时候更新一下版本了yapi升级了1.9.3

### ISSUE THREAD

**Issue by xikou1314** [fjc0k/docker-YApi#72]
https://github.com/YMFE/yapi/compare/v1.9.2...1.9.3

**Comment by naiba** [comment]
作者这个是自动更新的…… yapi release 的 tag 打的少了个 v，所以没能更新……

**Comment by JasonYH** [comment]
更新失败。。难受

**Comment by naiba** [comment]
开始编译了两位道友 快来看

**Comment by JasonYH** [comment]
哦吼 帅气

**Comment by JasonYH** [comment]
github acton 构建失败了。跟我自己拉下来仓库去构建一样的问题也是报这个错。看来要调整下构建了。作者大大

**Comment by fjc0k** [comment]
已更新并发布1.9.3

**Comment by JasonYH** [comment]
奶思！
