### ISSUE TITLE
1.9.3的构建失败了呀

### ISSUE THREAD

**Issue by JasonYH** [fjc0k/docker-YApi#73]
看到更新的是1.9.3了，然后流水线里的构建报错了

https://github.com/fjc0k/docker-YApi/runs/3045264111?check_suite_focus=true

这个错误跟我当时自己本地构建包的错一样。。。。我没能解决。。。

作者大大来排错呀。 😄

@fjc0k

**Comment by SunshowerC** [comment]
+1

**Comment by fjc0k** [comment]
已修复并发布 1.9.3
