### ISSUE TITLE
1.9.3 的 gitlab action Publish to Docker Hub 失败了

### ISSUE THREAD

**Issue by SunshowerC** [fjc0k/docker-YApi#74]
![image](https://user-images.githubusercontent.com/13402013/125434473-bfc9d782-e42c-4e39-8967-bc64ecf388f7.png)

**Comment by fjc0k** [comment]
已修复并发布 1.9.3

**Comment by JasonYH** [comment]
底部版本号没更新 但是代码的确是更新了。可能是官方的问题哈哈哈
![image](https://user-images.githubusercontent.com/18589230/125559287-f6160427-4771-47d6-aac6-30b7e5558ca7.png)
