### ISSUE TITLE
docker-compose pull yapi-web 后版本还是1.9.2

### ISSUE THREAD

**Issue by MRwangyd** [fjc0k/docker-YApi#75]
1、使用docker-compose 升级
docker-compose pull yapi-web \
  && docker-compose down \
  && docker-compose up -d

jayfong/yapi                                        <none>              004ec0d6cdca        13 months ago       251MB

2、使用以上方式部署后，还是1.9.2版本
![image](https://user-images.githubusercontent.com/27405334/125550537-5932c354-5ab2-4c2d-b230-348607998cdc.png)

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/125550622-f9bd83af-ef26-4f07-af98-cda302ae03ef.png)

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/125562657-9f9fa570-87e9-4911-9fc0-5fdd8bf94e0c.png)
