### ISSUE TITLE
不能升级yapi1.9.3

### ISSUE THREAD

**Issue by firek999** [fjc0k/docker-YApi#78]
使用如下代码升级
`docker-compose pull yapi-web \
  && docker-compose down \
  && docker-compose up -d`
完成以后前段仍然显示为1.9.2版本，是后续没有更新吗？

**Comment by firek999** [comment]
我看Dockerfile里面已经是1.9.3，想确认下，这是否只是前端显示的bug？

**Comment by fjc0k** [comment]
官方没改显示的版本，代码版本的确是1.9.3
