### ISSUE TITLE
开启高级mock-自定义脚本之后，调用报错，是什么问题

### ISSUE THREAD

**Issue by zhuxiangrong111** [fjc0k/docker-YApi#86]
版本: 1.10.2
![1](https://user-images.githubusercontent.com/62647662/144336721-e3690c42-47c4-4ee5-94c9-b2a3751fe218.png)
![2](https://user-images.githubusercontent.com/62647662/144336730-c8bf5801-6942-439b-abf6-70643ab877e6.png)

**Comment by zhuxiangrong111** [comment]
1

**Comment by zhuxiangrong111** [comment]
解决

**Comment by yyyThree** [comment]
> 解决
请问下老哥是怎么解决的，我也遇到了
