### ISSUE TITLE
怎么添加用户啊

### ISSUE THREAD

**Issue by gezhiwei8899** [fjc0k/docker-YApi#9]

**Comment by fjc0k** [comment]
https://github.com/fjc0k/docker-YApi#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

**Comment by fjc0k** [comment]
https://github.com/fjc0k/docker-YApi#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE

**Comment by gezhiwei8899** [comment]
![image](https://user-images.githubusercontent.com/16362526/71435379-ba3b2b80-2723-11ea-8b2d-cbe7050d8fb8.png)
炸了！

**Comment by gezhiwei8899** [comment]
![image](https://user-images.githubusercontent.com/16362526/71435412-df2f9e80-2723-11ea-84bf-8223b765c777.png)

**Comment by fjc0k** [comment]
你没用 gitlab 插件为啥要加上呢

**Comment by gezhiwei8899** [comment]
贪心了下 @fjc0k

**Comment by fjc0k** [comment]
那你去看 gitlab 插件的配置，配完全。

**Comment by gezhiwei8899** [comment]
可以的 棒！ @fjc0k

**Comment by gezhiwei8899** [comment]
![image](https://user-images.githubusercontent.com/16362526/71436926-5831f480-272a-11ea-980f-f96a62b32544.png)
不行啊 @fjc0k

**Comment by gezhiwei8899** [comment]
等待 MongoDB 服务可用...
安装 YApi 插件...
+ cd /yapi/vendors
+ npm install yapi-plugin-add-user --no-audit

npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.0.3 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.


+ yapi-plugin-add-user@0.0.1
added 1 package from 1 contributor in 29.347s


1 package is looking for funding
  run `npm fund` for details


+ npm run build-client


> yapi-vendor@1.8.5 build-client /yapi/vendors
> NODE_ENV=production ykit pack -m


Killed

尝试安装 YApi...
+ node '--unhandled-rejections=strict' ./vendors/server/install.js


/yapi/vendors/node_modules/mongoose/lib/error/validation.js:30
    Error.captureStackTrace(this);
          ^

Error [ValidationError]: user validation failed: username: Path `username` is required.
    at ValidationError.inspect (/yapi/vendors/node_modules/mongoose/lib/error/validation.js:59:24)
    at formatValue (internal/util/inspect.js:690:31)
    at inspect (internal/util/inspect.js:259:10)
    at afterInspector (internal/errors.js:676:14)
    at processPromiseRejections (internal/process/promises.js:192:9)
    at processTicksAndRejections (internal/process/task_queues.js:98:32) {
  errors: {
    username: MongooseError [ValidatorError]: Path `username` is required.
        at new ValidatorError (/yapi/vendors/node_modules/mongoose/lib/error/validator.js:29:11)
        at validate (/yapi/vendors/node_modules/mongoose/lib/schematype.js:838:13)
        at /yapi/vendors/node_modules/mongoose/lib/schematype.js:887:11
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/yapi/vendors/node_modules/mongoose/lib/schematype.js:847:19)
        at /yapi/vendors/node_modules/mongoose/lib/document.js:1844:9
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      message: 'Path `username` is required.',
      name: 'ValidatorError',
      properties: [Object],
      kind: 'required',
      path: 'username',
      value: '',
      reason: undefined,
      '$isValidatorError': true
    }
  },
  _message: 'user validation failed',
  name: 'ValidationError'
}

关闭引导服务...
尝试启动 YApi...
log: -------------------------------------swaggerSyncUtils constructor-----------------------------------------------
log: 服务已启动，请打开下面链接访问: 
http://127.0.0.1:3000/
log: mongodb load success...

**Comment by gezhiwei8899** [comment]
@fjc0k 加了一堆问题

**Comment by gezhiwei8899** [comment]
![image](https://user-images.githubusercontent.com/16362526/71437287-f4a8c680-272b-11ea-86f4-dec9815aa426.png)

**Comment by gezhiwei8899** [comment]
npm run build-client
yapi-vendor@1.8.5 build-client /yapi/vendors
NODE_ENV=production ykit pack -m
这一步好像经常卡死

**Comment by gezhiwei8899** [comment]
@fjc0k 大佬支撑一波呢

**Comment by fjc0k** [comment]
应该是机器配置或者分配给容器的配置不够，导致 `npm run build-client` 被杀死，后续也就出错了。

这是 YApi 自带的构建命令，没有办法改进的，建议换机器或调整配置部署。
