### ISSUE TITLE
找不到插件

### ISSUE THREAD

**Issue by qRainBirdp** [fjc0k/docker-YApi#96]
![1649227236(1)](https://user-images.githubusercontent.com/68057739/161911341-53ce2546-4d0d-4307-a8e5-d10e8248ec4f.png)
每一次通过docker-compose安装都是这个报错，不加插件项就能起来yapi，是内部地址信息过期了之类的问题么？
这个是docker-compose文件
![1649227360(1)](https://user-images.githubusercontent.com/68057739/161911648-ab0ecc29-c8d2-48b5-9e96-a86fe09f9a4b.png)
请教一下大佬！前段时间还没问题的，最近做备份重新docker-compose起了之后就起不来了

**Comment by Li-Weijian** [comment]
我也遇到相同情况，所有插件都安装不了

**Comment by chenchensheng** [comment]
看了下报错是前面安装插件的时候报错 node 版本低
我用 `node:12.22.12-alpine3.15` 重新打了个镜像 `chansonchan/yapi:latest` 可以先用着

**Comment by qRainBirdp** [comment]
我在第一次运行容器的时候运行了：
/usr/local/bin/node /opt/yarn-v1.22.4/bin/yarn.js config set ignore-engines true
然后restart容器，加了个ignore-engines后问题解决了。。。

**Comment by solxnp** [comment]
> 

我试了下，虽然不会报错，但是插件似乎并没有安装成功：项目设置页面没有安装的插件信息

**Comment by qRainBirdp** [comment]
这个应该不能解决本质问题，也可能和你的插件有关系，我用到的插件只有 interface-oauth2-token 和 notifier 这两个，我是安装成功了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fjc0k/docker-YApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 下午4:54
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [fjc0k/docker-YApi] 找不到插件 (Issue #96)





  
我在第一次运行容器的时候运行了： /usr/local/bin/node /opt/yarn-v1.22.4/bin/yarn.js config set ignore-engines true 然后restart容器，加了个ignore-engines后问题解决了。。。
  
我试了下，虽然不会报错，但是插件似乎并没有安装成功：项目设置页面没有安装的插件信息
